name: Update Pages
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Documentation"]
    types:
      - completed
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install DocFX
        run: choco install -y docfx
      - name: Copy CHANGELOG
        run: cp CHANGELOG.md Documentation~/changelog/CHANGELOG.md
      - name: Copy LICENSE
        run: cp LICENSE.md Documentation~/license/LICENSE.md
      - name: Copy Third Party Notices
        run: cp "Third Party Notices.md" "Documentation~/license/Third Party Notices.md"
      - name: Build
        run: docfx Documentation~/docfx.json
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
